// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.ShoeSizeConverter
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("input_size")]
        public long InputSize { get; set; }

        [JsonProperty("input_region")]
        public string InputRegion { get; set; }

        [JsonProperty("gender")]
        public string Gender { get; set; }

        [JsonProperty("conversions")]
        public Conversions Conversions { get; set; }

        [JsonProperty("note")]
        public string Note { get; set; }
    }

    public partial class Conversions
    {
        [JsonProperty("cm")]
        public double Cm { get; set; }

        [JsonProperty("jp")]
        public double Jp { get; set; }

        [JsonProperty("us")]
        public long Us { get; set; }

        [JsonProperty("uk")]
        public double Uk { get; set; }

        [JsonProperty("au")]
        public double Au { get; set; }

        [JsonProperty("eu")]
        public double Eu { get; set; }

        [JsonProperty("mx")]
        public double Mx { get; set; }

        [JsonProperty("kr")]
        public double Kr { get; set; }
    }
}
